# Generated by Django 2.1.7 on 2019-02-22 17:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('project04_app', '0002_auto_20190222_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centers',
            new_name='Center',
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='Centers',
            new_name='Center',
        ),
    ]
