# Generated by Django 2.1.7 on 2019-02-22 17:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('project04_app', '0003_auto_20190222_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Center',
            new_name='Centers',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='Center',
            new_name='Centers',
        ),
    ]
